# Generated by Django 3.1.4 on 2021-04-04 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0003_user_photourl'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notes',
        ),
    ]
