# Generated by Django 3.1.4 on 2021-04-04 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0004_delete_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='photoURl',
            new_name='photoURL',
        ),
    ]
